const books = [
    {
        author: 'Лао-цзы',
        name: 'Дао дэ цзин. Канон о Дао и дэ',
        publicationYear: 2022,
        price: '350 ₽',
        bestseller: true,
        available: false,
    },
    {
        author: 'Карл Саган',
        name: 'Космос',
        publicationYear: 2024,
        price: '250 ₽',
        bestseller: false,
        available: true,
    },
    {
        author: 'Баладжи Касал',
        name: 'Ошибки разумного инвестора',
        publicationYear: 2025,
        price: '450 ₽',
        bestseller: true,
        available: true,
    },
    {
        author: 'Марк Мансон',
        name: 'Тонкое искусство пофигизма',
        publicationYear: 2019,
        price: '400 ₽',
        bestseller: true,
        available: false,
    },
    {
        author: 'Фрэнк Герберт',
        name: 'Дюна',
        publicationYear: 2021,
        price: '600 ₽',
        bestseller: false,
        available: true,
    },
    {
        author: 'Джордж Оруэлл',
        name: '1984',
        publicationYear: 1949,
        price: '350 ₽',
        bestseller: true,
        available: true,
    },
    {
        author: 'Джулия Кэмерон',
        name: 'Путь художника',
        publicationYear: 2020,
        price: '500 ₽',
        bestseller: false,
        available: true,
    },
    {
        author: 'Ричард Докинз',
        name: 'Эгоистичный ген',
        publicationYear: 2018,
        price: '320 ₽',
        bestseller: true,
        available: false,
    },
    {
        author: 'Стивен Хокинг',
        name: 'Краткая история времени',
        publicationYear: 1988,
        price: '700 ₽',
        bestseller: true,
        available: true,
    },
    {
        author: 'Герман Гессе',
        name: 'Степной волк',
        publicationYear: 1927,
        price: '450 ₽',
        bestseller: false,
        available: true,
    }
];